### ISSUE TITLE
'Process exited before completing request'

### ISSUE THREAD

**Issue by Gys** [eawsy/aws-lambda-go-net#7] opened 2017-08-04 19:54 UTC
I get this error when I invoke the function ?

It happens in my test with the basic example code:
https://github.com/eawsy/aws-lambda-go-net/tree/master/_example/basic

If I invoke the function I get the error. It does not matter if I invoke from the commandline or using the API Gateway. Both give the same error.

Below the log of one test request, from both the API Gateway and AWS Lambda.

Any ideas what could go wrong ?

Execution log for request test-request
Fri Aug 04 18:55:13 UTC 2017 : Starting execution for request: test-invoke-request
Fri Aug 04 18:55:13 UTC 2017 : HTTP Method: GET, Resource Path: /
Fri Aug 04 18:55:13 UTC 2017 : Method request path: {}
Fri Aug 04 18:55:13 UTC 2017 : Method request query string: {}
Fri Aug 04 18:55:13 UTC 2017 : Method request headers: {}
Fri Aug 04 18:55:13 UTC 2017 : Method request body before transformations: 
Fri Aug 04 18:55:13 UTC 2017 : Endpoint request URI: https://lambda.eu-central-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:eu-central-1:061029286405:function:golang-preview/invocations
Fri Aug 04 18:55:13 UTC 2017 : Endpoint request headers: {x-amzn-lambda-integration-tag=test-request, Authorization=*********************************************************************************************************************************************************************************************************************************************************************************************************dbd72d, X-Amz-Date=20170804T185513Z, x-amzn-apigateway-api-id=c49ynl0n82, X-Amz-Source-Arn=arn:aws:execute-api:eu-central-1:061029286405:c49ynl0n82/null/GET/, Accept=application/json, User-Agent=AmazonAPIGateway_c49ynl0n82, X-Amz-Security-Token=[TRUNCATED]
Fri Aug 04 18:55:13 UTC 2017 : Endpoint request body after transformations: 
Fri Aug 04 18:55:13 UTC 2017 : Sending request to https://lambda.eu-central-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:eu-central-1:061029286405:function:golang-preview/invocations
Fri Aug 04 18:55:13 UTC 2017 : Received response. Integration latency: 112 ms
Fri Aug 04 18:55:13 UTC 2017 : Endpoint response body before transformations: {"errorMessage":"RequestId: 72a77d10-7946-11e7-b375-efd5be3a9346 Process exited before completing request"}
Fri Aug 04 18:55:13 UTC 2017 : Endpoint response headers: {x-amzn-Remapped-Content-Length=0, x-amzn-RequestId=72a77d10-7946-11e7-b375-efd5be3a9346, Connection=keep-alive, Content-Length=107, X-Amz-Function-Error=Unhandled, Date=Fri, 04 Aug 2017 18:55:13 GMT, X-Amzn-Trace-Id=root=1-5984c311-5177729f4c5c6d7167442086;sampled=0, Content-Type=application/json}
Fri Aug 04 18:55:13 UTC 2017 : Method response body after transformations: {"errorMessage":"RequestId: 72a77d10-7946-11e7-b375-efd5be3a9346 Process exited before completing request"}
Fri Aug 04 18:55:13 UTC 2017 : Method response headers: {X-Amzn-Trace-Id=sampled=0;root=1-5984c311-5177729f4c5c6d7167442086, Content-Type=application/json}
Fri Aug 04 18:55:13 UTC 2017 : Successfully completed execution
Fri Aug 04 18:55:13 UTC 2017 : Method completed with status: 200

AWS Lambda:

START RequestId: 72a77d10-7946-11e7-b375-efd5be3a9346 Version: $LATEST
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x7f0f111bccc0]
goroutine 17 [running, locked to thread]:
github.com/eawsy/aws-lambda-go-net/service/lambda/runtime/net/apigatewayproxy.(*Server).Handle(0xc420114460, 0xc42008edc0, 0x2, 0x8, 0xc4200ca200, 0x0, 0xc4200e7958, 0x7f0f137c6d0c)
/go/src/github.com/eawsy/aws-lambda-go-net/service/lambda/runtime/net/apigatewayproxy/server.go:115 +0xef0
github.com/eawsy/aws-lambda-go-net/service/lambda/runtime/net/apigatewayproxy.(*Server).Handle-fm(0xc42008edc0, 0x2, 0x8, 0xc4200ca200, 0x0, 0x0, 0x0)
/go/src/bitbucket.org/greulen/lambda-hello/main.go:15 +0x54
reflect.Value.call(0x7f0f1146aac0, 0x7f0f11604440, 0x193, 0x7f0f13887078, 0x4, 0xc4200e7e10, 0x2, 0x2, 0x7f0f13ab99c0, 0x7f0f13ae1368, ...)
/usr/local/go/src/reflect/value.go:434 +0x921
reflect.Value.Call(0x7f0f1146aac0, 0x7f0f11604440, 0x193, 0xc4200e7e10, 0x2, 0x2, 0xc4200ca278, 0x193, 0x7f0f137ddb48)
/usr/local/go/src/reflect/value.go:302 +0xa6
main.handle(0x7f0f13d91cd4, 0x7f0f17607254, 0xf15c04, 0xc4200e7eb0, 0xc4200e7eb8, 0x0)
/build/src/runtime.go:140 +0x4e1
main._cgoexpwrap_dd780bcacc70_handle(0x7f0f13d91cd4, 0x7f0f17607254, 0xf15c04, 0x0, 0x0, 0x0)
_/build/src/_obj/_cgo_gotypes.go:127 +0x9a
END RequestId: 72a77d10-7946-11e7-b375-efd5be3a9346
REPORT RequestId: 72a77d10-7946-11e7-b375-efd5be3a9346	Duration: 39.40 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 25 MB	
RequestId: 72a77d10-7946-11e7-b375-efd5be3a9346 Process exited before completing request

**Comment by fsenart** [comment] 2017-08-05 08:05
Hi @Gys can you please:
- provide the exact code snippet you are trying to run on your Lambda
- double check that you've configured you API Gateway in **proxy** mode

The fact is that you cannot directly, from the CLI, invoke your Lambda as this project waits for special info in the event provided to Lambda otherwise you can have nil pointer, etc. Moreover, the Lambda has to be behind an API Gateway configured in proxy mode one more time because the project waits for very specific info.
If you can provide your code + some cloudformation so I can reproduce your error, it would be perfect.
The provided examples works well when you configure your infra correctly, so please pay attention also to the provided SAM template to be sure all is ok at your side.

**Comment by charlieegan3** [comment] 2017-08-05 10:18
Just going to chime in here and say that I was having the same 'issue' last night - saw this comment this morning and used the test function in the API gateway and it worked as expected.

I had been trying to test my function in the lambda console and it wasn't working. Might be worth a short note in the readme?

For what it's worth - here's my Terraform config: https://github.com/charlieegan3/borked/tree/15623f8bbfdd2c60226a6e76d11656fdde259974/terraform just in case anyone else comes across this issue and is going that route...

Thanks @fsenart

**Comment by fsenart** [comment] 2017-08-05 10:50
@charlieegan3 thx for pointing out the lack of information. Hope the new README update makes things more clear.

**Comment by charlieegan3** [comment] 2017-08-05 12:30
That looks great yeah - didn't realise you could send an API gateway test event. Cheers.

Should probably still keep this open - seems the original question didn't work via the API Gateway either.

> It does not matter if I invoke from the commandline or using the API Gateway. Both give the same error.

**Comment by Gys** [comment] 2017-08-07 14:41
Thanks for the quick reply :-)

This solved it for me:
'the Lambda has to be behind an API Gateway configured in proxy mode'
I was not aware of the proxy mode. Also great to see the screenshots of testing with the gui.

For anyone else having this error: after correctly configuring the API Gateway with proxy mode, I still had the same error in CLI. Turns out the resulting API is expecting an extra element after being deployed.
Example:
curl https://yXXXXXX9.execute-api.eu-central-1.amazonaws.com/test/
Should be:
curl https://yXXXXXX9.execute-api.eu-central-1.amazonaws.com/test/something

**Comment by fsenart** [comment] 2017-08-08 07:00
@Gys the `something` part of the final url isn't mandatory. In the provided example there is a GET method on the root url without any additional path. So indeed, if you configure your http methods on a path the provided command won't work as expected. Please check that and tell me if you have still an error. 
I will close this one for the moment as the initial issue is resolved.

**Closed as completed by fsenart** 2017-08-08 07:00 UTC

**Comment by Gys** [comment] 2017-08-08 15:07
@fsenart Correct, its not needed. Sorry for the confusion !
